import { createContext, useContext, useState, useEffect, useMemo, ReactNode } from 'react';

type Language = 'FR' | 'EN' | 'AR';

interface LanguageContextType {
  currentLang: Language;
  setCurrentLang: (lang: Language) => void;
  t: (key: string) => string | any;
}

const allTranslations = {
  FR: {
    // Navigation
    home: 'Accueil',
    buy: 'Acheter',
    rent: 'Louer',
    shortStay: 'Court séjour',
    findDreamProperty: 'Trouvez la Propriété de Vos Rêves',
    buyHeroDescription: 'Découvrez des propriétés exceptionnelles à vendre à travers l\'Algérie avec nos conseils d\'experts.',
    findPerfectRental: 'Trouvez Votre Location Parfaite',
    rentHeroDescription: 'Explorez des propriétés locatives de qualité qui correspondent à votre style de vie et budget.',
    findPerfectStay: 'Trouvez Votre Séjour Parfait',
    shortStayHeroDescription: 'Réservez des hébergements uniques pour des séjours courts mémorables à travers l\'Algérie.',
    about: 'À propos',
    blog: 'Blog',
    login: 'Se connecter',
    publishProperty: 'Publier une annonce',
    myProfile: 'Mon profil',
    myBookings: 'Mes réservations',
    logout: 'Se déconnecter',
    
    // Hero
    heroTitle: 'Holibayt',
    heroSubtitle: 'Achetez. Louez. Vivez l\'Algérie autrement.',
    heroDescription: 'La première plateforme immobilière digitale nouvelle génération pour l\'Algérie.',
    
    // Quick Access
    buyProperty: 'Acheter un bien',
    rentProperty: 'Louer un logement',
    shortStayProperty: 'Court séjour',
    start: 'Commencer',
    bookNow: 'Réserver maintenant',
    
    // Property
    bedrooms: 'Chambres',
    bathrooms: 'Salles de bain',
    area: 'Surface',
    
    // Common
    search: 'Rechercher',
    cancel: 'Annuler',
    save: 'Enregistrer',
    clear: 'Effacer',
    viewDetails: 'Voir les détails',
    from: 'Du',
    to: 'Au',
    selectDate: 'Sélectionner une date',
    selectDates: 'Sélectionner des dates',
    
    // Login
    loginSuccess: 'Connexion réussie!',
    loginSuccessDesc: 'Vous êtes maintenant connecté à votre compte Holibayt.',
    loginDescription: 'Connectez-vous à votre compte Holibayt',
    email: 'Adresse email',
    emailPlaceholder: 'votre@email.com',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié?',
    noAccount: 'Vous n\'avez pas de compte?',
    createAccount: 'Créer un compte',
    
    // Pages
    propertiesForSale: 'Propriétés à Vendre',
    propertiesForSaleDesc: 'Découvrez nos meilleures propriétés disponibles à l\'achat',
    propertiesForRent: 'Propriétés à Louer',
    propertiesForRentDesc: 'Trouvez votre location idéale',
    shortStayTitle: 'Séjours Courts',
    shortStayDesc: 'Hébergements parfaits pour vos courts séjours',
    
    // Quick Access Section
    howCanWeHelp: 'Comment pouvons-nous vous aider ?',
    quickEntriesDesc: 'Des entrées rapides pour tous vos besoins immobiliers',
    buyPropertyTitle: 'Acheter un bien',
    buyPropertyDesc: 'Découvrez les meilleures opportunités à la vente',
    buyPropertySubtitle: 'Investissement & résidence principale',
    rentPropertyTitle: 'Louer un logement',
    rentPropertyDesc: 'Trouvez votre prochain chez-vous',
    rentPropertySubtitle: 'Location longue durée',
    shortStayTitle2: 'Court séjour',
    shortStayDesc2: 'Réservez votre hébergement pour quelques nuits',
    shortStaySubtitle: 'Vacances & voyages d\'affaires',
    needHelp: 'Besoin d\'aide pour faire votre choix ?',
    speakToAdvisor: 'Parler à un conseiller',
    
    // Services Section
    threeWaysToLive: 'Trois façons de vivre en Algérie',
    liveAlgeria: 'vivre l\'Algérie',
    platformDesc: 'Une plateforme unique pour tous vos besoins immobiliers. Que vous cherchiez à acheter, louer ou séjourner, nous vous accompagnons avec confiance et transparence.',
    buyTitle: 'Acheter',
    buySubtitle: 'Trouvez votre futur chez-vous',
    buyDescription: 'Découvrez une sélection rigoureuse de biens immobiliers vérifiés. De l\'appartement en centre-ville à la villa en bord de mer, trouvez le bien de vos rêves en Algérie.',
    rentTitle: 'Louer',
    rentSubtitle: 'Location longue durée',
    rentDescription: 'Que vous soyez étudiant, professionnel ou famille, trouvez votre location idéale avec des garanties de sécurité et des propriétaires de confiance.',
    stayTitle: 'Short Stay',
    staySubtitle: 'Séjours courts et vacances',
    stayDescription: 'L\'Airbnb algérien ! Réservez votre séjour parfait pour vos vacances, voyages d\'affaires ou visites familiales. Logements uniques et expériences authentiques.',
    explore: 'Explorer',
    whyChooseHolibayt: 'Pourquoi choisir Holibayt ?',
    securityGuaranteed: 'Sécurité garantie',
    securityDesc: 'Tous nos biens et utilisateurs sont vérifiés',
    premiumQuality: 'Qualité premium',
    qualityDesc: 'Une sélection rigoureuse pour votre satisfaction',
    support247: 'Support 24/7',
    supportDesc: 'Une équipe dédiée à votre service',
    
    // Home page sections
    seeAll: 'Voir tout',
    trendingAreas: 'Zones tendance',
    exploreByCities: 'Explorer par Villes',
    latestInsights: 'Dernières Actualités',
    featuredListings: 'Annonces en Vedette',
    findYourDreamHome: 'Trouvez Votre Maison de Rêve',
    flexibleLiving: 'Vie Flexible',
    exploreVerifiedProperties: 'Explorez les propriétés vérifiées',
    qualityRentalOptions: 'Options de location de qualité',
    holidayRentals: 'Locations de Vacances',
    perfectVacationStays: 'Séjours de vacances parfaits',
    
    // Hero placeholders and options
    cityNeighborhood: 'Ville, quartier ou adresse',
    whereToRent: 'Où cherchez-vous à louer ?',
    stayDestination: 'Destination de votre séjour',
    propertyType: 'Type de bien',
    apartment: 'Appartement',
    house: 'Maison',
    villa: 'Villa',
    land: 'Terrain',
    maxBudget: 'Budget max',
    housingType: 'Type de logement',
    studio: 'Studio',
    room: 'Chambre',
    maxRentMonth: 'Loyer max/mois',
    stayDates: 'Dates de séjour',
    stayDuration: 'Durée du séjour',
    night: 'nuit',
    nights: 'nuits',
    quickSelection: 'Sélection rapide',
    oneNight: '1 nuit',
    oneWeek: '1 semaine',
    weekend: 'Week-end',
    oneMonth: '1 mois',
    checkIn: 'Arrivée',
    checkOut: 'Départ',
    travelers: 'Voyageurs',
    availableProperties: 'Biens disponibles',
    satisfiedUsers: 'Utilisateurs satisfaits',
    wilayasCovered: 'Wilayas couvertes',
    
    // Footer translations
    footerDescription: 'Votre plateforme immobilière de confiance en Algérie',
    quickLinks: 'Liens rapides',
    services: 'Services',
    contact: 'Contact',
    propertyValuation: 'Évaluation immobilière',
    legalSupport: 'Support juridique',
    mortgageAdvice: 'Conseils hypothécaires',
    allRightsReserved: 'Tous droits réservés',
    
    // About page translations
    aboutBeitik: 'À propos de Holibayt',
    aboutDescription: 'Holibayt est la plateforme immobilière de référence en Algérie, connectant acheteurs, vendeurs et locataires depuis plus de 15 ans. Notre mission est de simplifier vos transactions immobilières.',
    properties: 'Propriétés',
    propertiesListed: 'Propriétés listées',
    clients: 'Clients',
    satisfiedClients: 'Clients satisfaits',
    experience: 'Expérience',
    years: 'ans',
    realEstateExpertise: 'D\'expertise immobilière',
    security: 'Sécurité',
    secureTransactions: 'Transactions sécurisées',
    ourStory: 'Notre Histoire',
    storyParagraph1: 'Fondée en 2009, Holibayt a révolutionné le marché immobilier algérien en créant la première plateforme en ligne dédiée à l\'immobilier en Algérie.',
    storyParagraph2: 'Nous avons commencé avec une vision simple : rendre l\'immobilier accessible à tous et faciliter les transactions entre particuliers et professionnels.',
    storyParagraph3: 'Aujourd\'hui, nous sommes fiers d\'être la plateforme de référence avec plus de 10,000 propriétés actives et une communauté de plus de 50,000 utilisateurs.',
    storyParagraph4: 'Notre équipe d\'experts travaille chaque jour pour améliorer votre expérience et vous accompagner dans vos projets immobiliers.',
    ourMission: 'Notre Mission',
    missionDescription: 'Démocratiser l\'accès à l\'immobilier en Algérie en offrant une plateforme moderne, sécurisée et facile à utiliser.',
    ourVision: 'Notre Vision',
    visionDescription: 'Devenir la référence incontournable de l\'immobilier au Maghreb et transformer la façon dont les gens achètent et louent.',
    ourValues: 'Nos Valeurs',
    valuesDescription: 'Transparence, confiance, innovation et service client d\'exception sont au cœur de tout ce que nous faisons.',
    
    // Publish property translations
    addPropertyDetails: 'Ajoutez les détails de votre propriété',
    propertyPublished: 'Propriété publiée!',
    propertySubmittedSuccess: 'Votre propriété a été soumise avec succès et sera examinée sous peu.',
    
    // Filter translations
    filters: 'Filtres',
    clearAll: 'Effacer Tout',
    allTypes: 'Tous Les Types',
    villaFilter: 'Villa',
    duplexFilter: 'Duplex',
    number: 'Nombre',
    minArea: 'Surface Min (m²)',
    maxArea: 'Surface Max (m²)',
    areaPlaceholder: 'Ex: 50',
    maxAreaPlaceholder: 'Ex: 200',
    minPrice: 'Prix Minimum',
    maxPrice: 'Prix Maximum',
    all: 'Tout',
    location: 'Localisation',
    cityOrDistrict: 'Ville Ou Quartier',
    
    // Property names and locations
    propertyNames: {
      luxuryApartment: 'Appartement de Luxe',
      modernApartment: 'Appartement Moderne',
      penthouse: 'Penthouse',
      seasideRental: 'Location Bord de Mer',
      shortStay: 'Court Séjour',
      studio: 'Studio',
      traditionalHouse: 'Maison Traditionnelle',
      villaMediterranean: 'Villa Méditerranéenne'
    },
    propertyLocations: {
      algiers: 'Alger',
      oran: 'Oran',
      constantine: 'Constantine',
      annaba: 'Annaba',
      tlemcen: 'Tlemcen',
      setif: 'Sétif',
      bejaia: 'Béjaïa',
      blida: 'Blida',
      hydra: 'Hydra',
      benAknoun: 'Ben Aknoun',
      birMouradRais: 'Bir Mourad Raïs',
      elBiar: 'El Biar',
      kouba: 'Kouba',
      bachdjerrah: 'Bachdjerrah',
      husseinDey: 'Hussein Dey',
      elHarrach: 'El Harrach'
    },
    
    // Cities and additional translations
    followUs: 'Suivez-nous',
    privacyPolicy: 'Politique de confidentialité',
    termsOfUse: 'Conditions d\'utilisation',
    cookies: 'Cookies',
    
    // Contact advisor translations
    chooseContactMethod: 'Choisissez votre méthode de contact préférée',
    multipleWaysConnect: 'Plusieurs façons de vous connecter avec nos conseillers experts',
    phoneSupport: 'Support téléphonique',
    speakDirectly: 'Parlez directement avec nos conseillers',
    emailSupport: 'Support par email',
    getDetailedAssistance: 'Obtenez une assistance détaillée par email',
    liveChat: 'Chat en direct',
    instantMessaging: 'Messagerie instantanée avec notre équipe',
    chatNow: 'Chatter maintenant',
    available247: 'Disponible 24/7',
    responseWithin2h: 'Réponse sous 2 heures',
    onlineNow: 'En ligne maintenant',
    expertAdvisors: 'Conseillers experts',
    averageRating: 'Note moyenne',
    averageResponseTime: 'Temps de réponse moyen',
    sendMessage: 'Envoyer un message',
    fullName: 'Nom complet',
    yourFullName: 'Votre nom complet',
    phoneNumber: 'Numéro de téléphone',
    subject: 'Sujet',
    whatCanWeHelp: 'Comment pouvons-nous vous aider?',
    message: 'Message',
    tellUsMore: 'Parlez-nous de vos besoins immobiliers...',
    ourOffice: 'Notre bureau',
    businessHours: 'Heures d\'ouverture',
    mondayFriday: 'Lundi - Vendredi: 8h00 - 20h00',
    saturday: 'Samedi: 9h00 - 18h00',
    sunday: 'Dimanche: 10h00 - 16h00',
    needImmediateHelp: 'Besoin d\'aide immédiate?',
    call247Hotline: 'Appelez notre ligne d\'urgence 24/7',
    
    // Property and publish property translations
    propertyTypeTranslation: 'Type de Propriété',
    forSale: 'À Vendre', 
    forRent: 'À Louer',
    shortStayRent: 'Court Séjour',
    basicInformation: 'Informations de Base',
    propertyTitleField: 'Titre de la Propriété',
    propertyTitlePlaceholder: 'Ex: Belle villa avec jardin',
    categoryField: 'Catégorie',
    selectCategory: 'Sélectionner la catégorie',
    duplex: 'Duplex',
    hotel: 'Hôtel',
    guesthouse: 'Maison d\'hôtes',
    locationField: 'Localisation',
    cityField: 'Ville',
    district: 'Quartier/Zone',
    fullAddress: 'Adresse Complète',
    propertyDetailsTitle: 'Détails de la Propriété',
    chambers: 'Chambres',
    numberField: 'Nombre',
    areaField: 'Surface (m²)',
    floorField: 'Étage',
    floorExample: 'Ex: 2ème',
    pricing: 'Prix',
    priceDZD: 'Prix (DZD)',
    priceExample: 'Ex: 2,500,000',
    priceTypeField: 'Type de Prix',
    totalPrice: 'Prix total',
    monthlyPrice: 'Par mois',
    dailyPrice: 'Par jour',
    weeklyPrice: 'Par semaine',
    featuresAmenities: 'Caractéristiques et Équipements',
    parkingFeature: 'Parking',
    swimmingPoolFeature: 'Piscine',
    gardenFeature: 'Jardin',
    balconyFeature: 'Balcon',
    elevatorFeature: 'Ascenseur',
    securityFeature: 'Sécurité',
    furnishedFeature: 'Meublé',
    airConditioningFeature: 'Climatisation',
    // Property features
    privatePool: "Piscine privée",
    landscapedGarden: "Jardin paysager",
    garage2Cars: "Garage 2 voitures",
    alarmSystem: "Système d'alarme",
    airConditioning: "Climatisation",
    equippedKitchen: "Cuisine équipée",

    // Property page specific keys
    locationTitle: "Localisation",
    mapboxHint: "Pour afficher la carte interactive, veuillez entrer votre token Mapbox public. Vous pouvez l'obtenir sur",
    mapboxTokenPlaceholder: "Votre token Mapbox public",
    loadMap: "Charger la carte",
    addressLabel: "Adresse",
    detailsLabel: "Détails",
    nearbyShops: "Commerces",
    nearbyShopsNote: "À proximité",
    transport: "Transport",
    transportAccessible: "Accessible",
    callBtn: "Appeler",
    sendMessageBtn: "Envoyer un message",
    descriptionField: 'Description',
    detailedDescription: 'Description Détaillée',
    describeProperty: 'Décrivez votre propriété en détail...',
    contactInformationTitle: 'Informations de Contact',
    fullNameField: 'Nom Complet',
    phoneNumberField: 'Numéro de Téléphone',
    propertyPhotos: 'Photos de la Propriété',
    uploadPhotos: 'Téléchargez vos photos',
    dragDropImages: 'Glissez-déposez vos images ici ou cliquez pour sélectionner (Max 10 images)',
    selectImages: 'Sélectionner des Images',
    publishPropertyBtn: 'Publier la Propriété',
    completed: 'Complété',
    incompleteStep: 'Étape incomplète',
    completeRequiredFields: 'Veuillez compléter tous les champs requis',
    next: 'Suivant',
    previous: 'Précédent',
    
    // Property page translations
    contactOwner: 'Contacter le Propriétaire',
    characteristics: 'Caractéristiques',
    listingDetails: 'Détails de l\'Annonce',
    reference: 'Référence',
    typeField: 'Type',
    publishedOn: 'Publié le',
    lastUpdated: 'Dernière mise à jour',
    daysAgo: 'il y a 2 jours',
    // Cities translations
    exploreByTitle: 'Explorez par',
    citiesTitle: 'Villes',
    citiesDescription: 'Découvrez les meilleures opportunités immobilières dans les principales villes d\'Algérie',
    discoverCity: 'Découvrir',
    allCitiesAvailable: 'Toutes les villes disponibles',
    moreThanCitiesAvailable: 'Plus de 20 villes disponibles',
    showLess: 'Voir moins',
    seeAllCities: 'Voir toutes les villes',
    
    // City descriptions
    algerDescription: 'La capitale dynamique de l\'Algérie',
    oranDescription: 'La perle de l\'Ouest algérien',
    constantineDescription: 'La ville des ponts suspendus',
    annabaDescription: 'La cité du jujubier',
    setifDescription: 'Ville des hautes plaines',
    tlemcenDescription: 'Perle du Maghreb',
    bejaiaDescription: 'Fiancée de la Méditerranée',
    blidaDescription: 'Ville des roses',
    
    // Blog translations
    blogInsights: 'Blog & Actualités',
    blogDescription: 'Restez informé des dernières tendances, conseils et analyses du marché immobilier algérien',
    stayUpdated: 'Restez Informé',
    newsletterDescription: 'Abonnez-vous à notre newsletter et ne manquez jamais les dernières analyses immobilières',
    enterEmail: 'Entrez votre email',
    subscribe: 'S\'abonner',
    backToBlog: "Retour au Blog",
    
    // Property types
    propertyVilla: 'Villa',
    propertyAppartement: 'Appartement', 
    propertyDuplex: 'Duplex',
    propertyMaison: 'Maison',
    propertyStudio: 'Studio',
    propertyLoft: 'Loft',
    propertyChambre: 'Chambre',
    propertySuite: 'Suite',
    propertyPenthouse: 'Penthouse',
    
    // Pricing units
    currencyDA: 'DA',
    currencyPerMonth: 'DA/mois',
    currencyPerNight: 'DA/nuit',

    // Property names
    villaMediterranean: "Villa Méditerranéenne",
    luxuryApartment: "Appartement de Luxe",
    modernApartment: "Appartement Moderne",
    villaModern: "Villa Moderne",
    duplexFamily: "Duplex Familial",
    traditionalHouse: "Maison Traditionnelle",
    modernStudio: "Studio Moderne",
    apartmentStanding: "Appartement Standing",
    villaWithPool: "Villa avec Piscine",
    villaWithGarden: "Villa avec Jardin",
    studioCenterCity: "Studio Centre-Ville",
    individualHouse: "Maison Individuelle",
    newApartment: "Appartement Neuf",
    industrialLoft: "Loft Industriel",
    studioShortStay: "Studio Courts Séjours",
    seaViewApartment: "Appartement Vue Mer",
    holidayVilla: "Villa de Vacances",
    guestRoom: "Chambre d'Hôte",
    modernLoft: "Loft Moderne",
    familySuite: "Suite Familiale",
    penthouseSeaView: "Penthouse Vue Mer",

    // Locations
    algerAlgeria: "Alger, Algérie",
    oranAlgeria: "Oran, Algérie",
    constantineAlgeria: "Constantine, Algérie",
    tlemcenAlgeria: "Tlemcen, Algérie",
    setifAlgeria: "Sétif, Algérie",
    bejaiaAlgeria: "Béjaïa, Algérie",
    annabaAlgeria: "Annaba, Algérie",
    tipazaAlgeria: "Tipaza, Algérie",
    algerCentreAlgeria: "Alger Centre, Algérie",

    publishedBy: 'Publié par',
    readMore: 'Lire plus',
    
    // Additional translations
    habitants: 'habitants',
    algeria: 'Algérie',
    tenthCentury: 'Xe siècle',
    thirdMillenniumBC: 'IIIe millénaire av. J.-C.',
    twelfthCenturyBC: 'XIIe siècle av. J.-C.',
    
    // City names
    cityAlger: 'Alger',
    cityOran: 'Oran',
    cityConstantine: 'Constantine',
    cityAnnaba: 'Annaba',

    // Metrics labels
    verifiedLabel: "100% vérifié",
    ratingLabel: "Note 4,8/5",
    responseTimeLabel: "Réponse ≤ 2h",
    hoursAbbrev: "h",
    whyChooseDesc: "Découvrez pourquoi des milliers d'utilisateurs nous font confiance pour leurs projets immobiliers.",

    // Service CTAs
    exploreBuy: "Découvrir Achat",
    exploreRent: "Découvrir Location",
    exploreShortStay: "Découvrir Court séjour",

    // Buy bullets
    buy_feat_verified: "Tous nos biens et utilisateurs sont vérifiés",
    buy_feat_virtualTour: "Visite virtuelle",
    buy_feat_financing: "Financement facilité",
    buy_feat_legal: "Accompagnement juridique",

    // Rent bullets
    rent_feat_secureContracts: "Contrats sécurisés",
    rent_feat_paymentGuarantee: "Garantie de paiement",
    rent_feat_digitalInspection: "État des lieux numérique",
    rent_feat_dedicatedTeam: "Équipe dédiée à votre service",

    // Short Stay bullets
    stay_feat_verifiedHosts: "Hôtes vérifiés",
    stay_feat_instantBooking: "Réservation instantanée",
    stay_feat_localExperiences: "Expériences locales",
    stay_feat_travelInsurance: "Assurance voyage",
    citySetif: 'Sétif',
    cityTlemcen: 'Tlemcen',
    cityBejaia: 'Béjaïa',
    cityBlida: 'Blida',
    
    // City page sections
    historyHeritage: 'Histoire & patrimoine',
    population: 'Population',
    inhabitantsShort: 'habitants',
    cityArea: 'Superficie',
    foundedIn: 'Fondée en',
    propertiesAvailableIn: 'Propriétés disponibles à',
    
    // City histories
    oranHistory: 'Oran est une ville côtière du nord-ouest algérien, connue pour son port, la musique raï et un patrimoine mêlant influences françaises et espagnoles. La corniche moderne et les quartiers historiques en font un pôle culturel.',
    algerHistory: 'Alger, la capitale, mêle influences ottomanes, coloniales françaises et modernes ; la Casbah est classée UNESCO.',
    constantineHistory: 'Constantine est célèbre pour ses gorges spectaculaires et ses ponts suspendus, qui ont façonné son histoire.',
    annabaHistory: 'Annaba, sur la Méditerranée, est réputée pour ses plages, l\'héritage de Saint Augustin et un port en développement.',
    
    // Blog categories
    allCategories: 'Toutes',
    marketTrends: 'Tendances du Marché',
    buyingGuide: 'Guide d\'Achat',
    investment: 'Investissement',
    finance: 'Finance',
    renovation: 'Rénovation',
    legal: 'Juridique',
    
    // Blog post titles
    blogTitle1: 'L\'Avenir de l\'Immobilier en Algérie',
    blogTitle2: 'Comment Choisir l\'Emplacement Parfait',
    blogTitle3: 'Courts Séjours : Une Opportunité Croissante',
    blogTitle4: 'Comprendre l\'Évaluation Immobilière en Algérie',
    blogTitle5: 'Conseils de Rénovation pour un ROI Maximum',
    blogTitle6: 'Considérations Juridiques pour les Acheteurs',
    
    // Blog excerpts
    blogExcerpt1: 'Découvrez les tendances émergentes et les opportunités du marché immobilier algérien en croissance.',
    blogExcerpt2: 'Un guide complet pour sélectionner l\'emplacement idéal pour votre prochain investissement immobilier.',
    blogExcerpt3: 'Explorez le marché en pleine expansion des locations courtes et comment maximiser vos rendements d\'investissement.',
    blogExcerpt4: 'Apprenez les facteurs clés qui déterminent la valeur des propriétés dans différentes villes algériennes.',
    blogExcerpt5: 'Stratégies de rénovation intelligentes qui peuvent considérablement augmenter la valeur de votre propriété.',
    blogExcerpt6: 'Aspects juridiques essentiels que tout acheteur de propriété devrait connaître avant de faire un achat.',
    
    // Blog authors
    author1: 'Sarah Benali',
    author2: 'Ahmed Mansouri', 
    author3: 'Fatima Ouali',
    author4: 'Karim Hakim',
    author5: 'Leila Benaissa',
    author6: 'Mohamed Kaci',

    // Host dashboard translations
    host: {
      dashboard: 'Tableau de bord',
      welcomeMessage: 'Bienvenue dans votre espace hôte',
      activeProperties: 'Propriétés actives',
      messagesReceived: 'Messages reçus',
      monthlyRevenue: 'Revenus ce mois',
      checkMessages: 'Consultez vos messages',
      quickActions: 'Actions rapides',
      publishProperty: 'Publier une propriété',
      viewListings: 'Voir mes annonces',
      messages: 'Messages',
      recentProperties: 'Dernières propriétés',
      publishedOn: 'Publié le',
      active: 'Actif',
      inactive: 'Inactif',
      loadingProperties: 'Chargement de vos propriétés...',
      // Listings page
      listings: 'Mes Annonces',
      manageProperties: 'Gérez vos propriétés et leurs performances',
      newListing: 'Nouvelle Annonce',
      postProperty: 'Publier une Propriété',
      activeListings: 'Annonces Actives',
      totalMessages: 'Total Messages',
      totalViews: 'Total Vues',
      thisMonth: 'Ce mois',
      view: 'Voir',
      edit: 'Modifier',
      createdOn: 'Créé le',
      noListingsYet: 'Aucune annonce encore',
      createFirstListing: 'Créez votre première annonce pour commencer à recevoir des demandes',
      createMyFirstListing: 'Créer ma première annonce',
      confirmDelete: 'Êtes-vous sûr de vouloir supprimer cette propriété?',
      // Messages page
      messagesPage: 'Messages',
      manageContactRequests: 'Gérez les demandes de contact pour vos propriétés',
      unreadMessages: 'Messages non lus',
      responseRate: 'Taux de réponse',
      newStatus: 'Nouveau',
      readStatus: 'Lu',
      repliedStatus: 'Répondu',
      archivedStatus: 'Archivé',
      markAsRead: 'Marquer comme lu',
      reply: 'Répondre',
      call: 'Appeler',
      archive: 'Archiver',
      noMessages: 'Aucun message',
      noContactRequests: 'Vous n\'avez reçu aucune demande de contact pour le moment.',
      loadingMessages: 'Chargement des messages...',
      calendar: 'Calendrier des Propriétés'
    },
    
    satisfactionRate: 'Taux de satisfaction',
    back: 'Retour',
    selectCurrency: 'Choisir la devise',

    // Admin translations
    admin: {
      dashboard: 'Tableau de bord',
      properties: 'Propriétés',  
      users: 'Utilisateurs',
      messages: 'Messages',
      settings: 'Paramètres',
      hostsGuests: 'Hôtes et Invités',
      administration: 'Administration',
      adminConsole: 'Console Admin',
      backToSite: 'Retour au site',
      logout: 'Déconnexion',
      userManagement: 'Gestion des Utilisateurs',
      manageUsersHosts: 'Gérez les utilisateurs, hôtes et leurs statuts',
      newUser: 'Nouvel Utilisateur',
      totalUsers: 'Total Utilisateurs',
      ofTotal: 'du total',
      allRoles: 'Tous les rôles',
      allStatuses: 'Tous les statuts',
      searchByNameEmail: 'Rechercher par nom ou email...',
      adminPanel: 'Panneau Admin',
      overviewPlatform: 'Aperçu des performances de votre plateforme',
      totalProperties: 'Total Propriétés',
      activeProperties: 'Propriétés Actives',
      recentProperties: 'Propriétés Récentes',
      propertyDistribution: 'Distribution des Propriétés',
      propertyManagement: 'Gestion des Propriétés',
      manageAllProperties: 'Gérer toutes les propriétés de la plateforme',
      export: 'Exporter',
      newProperty: 'Nouvelle Propriété',
      totalRegistered: 'Total enregistré',
      needsValidation: 'Nécessite validation',
      issuesDetected: 'Problèmes détectés',
      searchByTitle: 'Rechercher par titre, propriétaire ou lieu...',
      searchByName: 'Rechercher par nom ou email...',
      allStatus: 'Tous les statuts',
      allTypes: 'Tous les types',
      active: 'Actif',
      activeHosts: 'Hôtes Actifs',
      pending: 'En attente',
      suspended: 'Suspendu',
      forSale: 'À vendre',
      forRent: 'À louer',
      shortStay: 'Court séjour',
      view: 'Voir',
      thisMonth: 'ce mois',
      propertiesPublished: 'Propriétés publiées',
      fromLastWeek: 'de la semaine dernière'
    }
  },
  EN: {
    // Navigation
    home: 'Home',
    buy: 'Buy',
    rent: 'Rent',
    shortStay: 'Short Stay',
    findDreamProperty: 'Find Your Dream Property',
    buyHeroDescription: 'Discover exceptional properties for sale across Algeria with our expert guidance.',
    findPerfectRental: 'Find Your Perfect Rental',
    rentHeroDescription: 'Explore quality rental properties that match your lifestyle and budget.',
    findPerfectStay: 'Find Your Perfect Stay',
    shortStayHeroDescription: 'Book unique accommodations for memorable short-term stays across Algeria.',
    about: 'About',
    blog: 'Blog',
    login: 'Login',
    publishProperty: 'Publish Property',
    myProfile: 'My Profile',
    myBookings: 'My Bookings',
    logout: 'Logout',
    
    // Hero
    heroTitle: 'Holibayt',
    heroSubtitle: 'Buy. Rent. Live Algeria differently.',
    heroDescription: 'The first next-generation digital real estate platform for Algeria.',
    
    // Quick Access
    buyProperty: 'Buy a property',
    rentProperty: 'Rent a home',
    shortStayProperty: 'Short stay',
    start: 'Start',
    bookNow: 'Book now',
    
    // Property
    bedrooms: 'Bedrooms',
    bathrooms: 'Bathrooms',
    area: 'Area',
    
    // Common
    search: 'Search',
    cancel: 'Cancel',
    save: 'Save',
    clear: 'Clear',
    viewDetails: 'View Details',
    from: 'From',
    to: 'To',
    selectDate: 'Select date',
    selectDates: 'Select dates',
    
    // Login
    loginSuccess: 'Login successful!',
    loginSuccessDesc: 'You are now logged in to your Holibayt account.',
    loginDescription: 'Sign in to your Holibayt account',
    email: 'Email address',
    emailPlaceholder: 'your@email.com',
    password: 'Password',
    forgotPassword: 'Forgot password?',
    noAccount: 'Don\'t have an account?',
    createAccount: 'Create account',
    
    // Pages
    propertiesForSale: 'Properties for Sale',
    propertiesForSaleDesc: 'Discover our best properties available for purchase',
    propertiesForRent: 'Properties for Rent',
    propertiesForRentDesc: 'Find your ideal rental',
    shortStayTitle: 'Short Stays',
    shortStayDesc: 'Perfect accommodations for your short stays',
    
    // Quick Access Section
    howCanWeHelp: 'How can we help you?',
    quickEntriesDesc: 'Quick entries for all your real estate needs',
    buyPropertyTitle: 'Buy a property',
    buyPropertyDesc: 'Discover the best opportunities for sale',
    buyPropertySubtitle: 'Investment & main residence',
    rentPropertyTitle: 'Rent a home',
    rentPropertyDesc: 'Find your next home',
    rentPropertySubtitle: 'Long-term rental',
    shortStayTitle2: 'Short stay',
    shortStayDesc2: 'Book your accommodation for a few nights',
    shortStaySubtitle: 'Vacations & business trips',
    needHelp: 'Need help making your choice?',
    speakToAdvisor: 'Speak to an advisor',
    
    // Services Section
    threeWaysToLive: 'Three ways to live in Algeria',
    liveAlgeria: 'live Algeria',
    platformDesc: 'A unique platform for all your real estate needs. Whether you\'re looking to buy, rent or stay, we support you with confidence and transparency.',
    buyTitle: 'Buy',
    buySubtitle: 'Find your future home',
    buyDescription: 'Discover a rigorous selection of verified real estate properties. From city center apartments to seaside villas, find your dream property in Algeria.',
    rentTitle: 'Rent',
    rentSubtitle: 'Long-term rental',
    rentDescription: 'Whether you\'re a student, professional or family, find your ideal rental with security guarantees and trusted landlords.',
    stayTitle: 'Short Stay',
    staySubtitle: 'Short stays and vacations',
    stayDescription: 'The Algerian Airbnb! Book your perfect stay for your vacations, business trips or family visits. Unique accommodations and authentic experiences.',
    explore: 'Explore',
    whyChooseHolibayt: 'Why choose Holibayt?',
    securityGuaranteed: 'Security guaranteed',
    securityDesc: 'All our properties and users are verified',
    premiumQuality: 'Premium quality',
    qualityDesc: 'A rigorous selection for your satisfaction',
    support247: 'Support 24/7',
    supportDesc: 'A team dedicated to your service',
    
    // Home page sections
    seeAll: 'See all',
    trendingAreas: 'Trending Areas',
    exploreByCities: 'Explore by Cities',
    latestInsights: 'Latest Insights',
    featuredListings: 'Featured Listings',
    findYourDreamHome: 'Find Your Dream Home',
    flexibleLiving: 'Flexible Living',
    exploreVerifiedProperties: 'Explore verified properties',
    qualityRentalOptions: 'Quality rental options',
    holidayRentals: 'Holiday Rentals',
    perfectVacationStays: 'Perfect vacation stays',
    
    // Hero placeholders and options
    cityNeighborhood: 'City, neighborhood or address',
    whereToRent: 'Where are you looking to rent?',
    stayDestination: 'Your stay destination',
    propertyType: 'Property type',
    apartment: 'Apartment',
    house: 'House',
    villa: 'Villa',
    land: 'Land',
    maxBudget: 'Max budget',
    housingType: 'Housing type',
    studio: 'Studio',
    room: 'Room',
    maxRentMonth: 'Max rent/month',
    stayDates: 'Stay dates',
    stayDuration: 'Stay duration',
    night: 'night',
    nights: 'nights', 
    quickSelection: 'Quick selection',
    oneNight: '1 night',
    oneWeek: '1 week',
    weekend: 'Weekend',
    oneMonth: '1 month',
    checkIn: 'Check-in', 
    checkOut: 'Check-out',
    travelers: 'Travelers',
    availableProperties: 'Available properties',
    satisfiedUsers: 'Satisfied users',
    wilayasCovered: 'Wilayas covered',
    
    // Footer translations
    footerDescription: 'Your trusted real estate platform in Algeria',
    quickLinks: 'Quick Links',
    services: 'Services',
    contact: 'Contact',
    propertyValuation: 'Property valuation',
    legalSupport: 'Legal support',
    mortgageAdvice: 'Mortgage advice',
    allRightsReserved: 'All rights reserved',
    
    // About page translations
    aboutBeitik: 'About Holibayt',
    aboutDescription: 'Holibayt is Algeria\'s leading real estate platform, connecting buyers, sellers and tenants for over 15 years. Our mission is to simplify your real estate transactions.',
    properties: 'Properties',
    propertiesListed: 'Properties listed',
    clients: 'Clients',
    satisfiedClients: 'Satisfied clients',
    experience: 'Experience',
    years: 'years',
    realEstateExpertise: 'Of real estate expertise',
    security: 'Security',
    secureTransactions: 'Secure transactions',
    ourStory: 'Our Story',
    storyParagraph1: 'Founded in 2009, Holibayt revolutionized the Algerian real estate market by creating the first online platform dedicated to real estate in Algeria.',
    storyParagraph2: 'We started with a simple vision: make real estate accessible to everyone and facilitate transactions between individuals and professionals.',
    storyParagraph3: 'Today, we are proud to be the reference platform with more than 10,000 active properties and a community of more than 50,000 users.',
    storyParagraph4: 'Our team of experts works every day to improve your experience and support you in your real estate projects.',
    ourMission: 'Our Mission',
    missionDescription: 'Democratize access to real estate in Algeria by offering a modern, secure and easy-to-use platform.',
    ourVision: 'Our Vision',
    visionDescription: 'Become the essential reference for real estate in the Maghreb and transform the way people buy and rent.',
    ourValues: 'Our Values',
    valuesDescription: 'Transparency, trust, innovation and exceptional customer service are at the heart of everything we do.',
    
    // Publish property translations
    addPropertyDetails: 'Add your property details',
    propertyPublished: 'Property published!',
    propertySubmittedSuccess: 'Your property has been successfully submitted and will be reviewed shortly.',
    
    // Filter translations
    filters: 'Filters',
    clearAll: 'Clear All',
    allTypes: 'All Types',
    villaFilter: 'Villa',
    duplexFilter: 'Duplex',
    number: 'Number',
    minArea: 'Min Area (m²)',
    maxArea: 'Max Area (m²)',
    areaPlaceholder: 'Ex: 50',
    maxAreaPlaceholder: 'Ex: 200',
    minPrice: 'Minimum Price',
    maxPrice: 'Maximum Price',
    all: 'All',
    location: 'Location',
    cityOrDistrict: 'City Or District',
    
    // Property names and locations
    propertyNames: {
      luxuryApartment: 'Luxury Apartment',
      modernApartment: 'Modern Apartment',
      penthouse: 'Penthouse',
      seasideRental: 'Seaside Rental',
      shortStay: 'Short Stay',
      studio: 'Studio',
      traditionalHouse: 'Traditional House',
      villaMediterranean: 'Mediterranean Villa'
    },
    propertyLocations: {
      algiers: 'Algiers',
      oran: 'Oran',
      constantine: 'Constantine',
      annaba: 'Annaba',
      tlemcen: 'Tlemcen',
      setif: 'Setif',
      bejaia: 'Bejaia',
      blida: 'Blida',
      hydra: 'Hydra',
      benAknoun: 'Ben Aknoun',
      birMouradRais: 'Bir Mourad Rais',
      elBiar: 'El Biar',
      kouba: 'Kouba',
      bachdjerrah: 'Bachdjerrah',
      husseinDey: 'Hussein Dey',
      elHarrach: 'El Harrach'
    },
    
    // Cities and additional translations
    followUs: 'Follow us',
    privacyPolicy: 'Privacy Policy',
    termsOfUse: 'Terms of Use',
    cookies: 'Cookies',
    
    // Contact advisor translations
    chooseContactMethod: 'Choose Your Preferred Contact Method',
    multipleWaysConnect: 'Multiple ways to connect with our expert advisors',
    phoneSupport: 'Phone Support',
    speakDirectly: 'Speak directly with our advisors',
    emailSupport: 'Email Support',
    getDetailedAssistance: 'Get detailed assistance via email',
    liveChat: 'Live Chat',
    instantMessaging: 'Instant messaging with our team',
    chatNow: 'Chat Now',
    available247: '24/7 Available',
    responseWithin2h: 'Response within 2 hours',
    onlineNow: 'Online now',
    expertAdvisors: 'Expert Advisors',
    averageRating: 'Average Rating',
    averageResponseTime: 'Average Response Time',
    sendMessage: 'Send Message',
    fullName: 'Full Name',
    yourFullName: 'Your full name',
    phoneNumber: 'Phone Number',
    subject: 'Subject',
    whatCanWeHelp: 'What can we help you with?',
    message: 'Message',
    tellUsMore: 'Tell us more about your property needs...',
    ourOffice: 'Our Office',
    businessHours: 'Business Hours',
    mondayFriday: 'Monday - Friday: 8:00 AM - 8:00 PM',
    saturday: 'Saturday: 9:00 AM - 6:00 PM',
    sunday: 'Sunday: 10:00 AM - 4:00 PM',
    needImmediateHelp: 'Need Immediate Help?',
    call247Hotline: 'Call our 24/7 emergency hotline',
    
    // Property and publish property translations
    propertyTypeTranslation: 'Property Type',
    forSale: 'For Sale',
    forRent: 'For Rent', 
    shortStayRent: 'Short Stay',
    basicInformation: 'Basic Information',
    propertyTitleField: 'Property Title',
    propertyTitlePlaceholder: 'Ex: Beautiful villa with garden',
    categoryField: 'Category',
    selectCategory: 'Select category',
    duplex: 'Duplex',
    hotel: 'Hotel',
    guesthouse: 'Guesthouse',
    locationField: 'Location',
    cityField: 'City',
    district: 'District/Area',
    fullAddress: 'Full Address',
    propertyDetailsTitle: 'Property Details',
    chambers: 'Bedrooms',
    numberField: 'Number',
    areaField: 'Area (m²)',
    floorField: 'Floor',
    floorExample: 'Ex: 2nd',
    pricing: 'Pricing',
    priceDZD: 'Price (DZD)',
    priceExample: 'Ex: 2,500,000',
    priceTypeField: 'Price Type',
    totalPrice: 'Total price',
    monthlyPrice: 'Per month',
    dailyPrice: 'Per day',
    weeklyPrice: 'Per week',
    featuresAmenities: 'Features & Amenities',
    parkingFeature: 'Parking',
    swimmingPoolFeature: 'Swimming Pool',
    gardenFeature: 'Garden',
    balconyFeature: 'Balcony',
    elevatorFeature: 'Elevator',
    securityFeature: 'Security',
    furnishedFeature: 'Furnished',
    airConditioningFeature: 'Air Conditioning',
    gymFeature: 'Gym',
    descriptionField: 'Description',
    detailedDescription: 'Detailed Description',
    describeProperty: 'Describe your property in detail...',
    contactInformationTitle: 'Contact Information',
    fullNameField: 'Full Name',
    phoneNumberField: 'Phone Number',
    propertyPhotos: 'Property Photos',
    uploadPhotos: 'Upload your photos',
    dragDropImages: 'Drag and drop your images here or click to select (Max 10 images)',
    selectImages: 'Select Images',
    publishPropertyBtn: 'Publish Property',
    completed: 'Completed',
    incompleteStep: 'Incomplete step',
    completeRequiredFields: 'Please complete all required fields',
    next: 'Next',
    previous: 'Previous',
    
    // Property page translations
    contactOwner: 'Contact Owner',
    characteristics: 'Characteristics',
    listingDetails: 'Listing Details',
    reference: 'Reference',
    typeField: 'Type',
    publishedOn: 'Published on',
    lastUpdated: 'Last updated',
    daysAgo: '2 days ago',

    // Property page specific keys
    locationTitle: "Location",
    mapboxHint: "To display the interactive map, please enter your public Mapbox token. You can get it at",
    mapboxTokenPlaceholder: "Your public Mapbox token",
    loadMap: "Load map",
    addressLabel: "Address",
    detailsLabel: "Details",
    nearbyShops: "Shops",
    nearbyShopsNote: "Nearby",
    transport: "Transport",
    transportAccessible: "Accessible",
    callBtn: "Call",
    sendMessageBtn: "Send Message",

    // Property features
    privatePool: "Private pool",
    landscapedGarden: "Landscaped garden",
    garage2Cars: "2-car garage",
    alarmSystem: "Alarm system",
    airConditioning: "Air conditioning",
    equippedKitchen: "Equipped kitchen",
    // Cities translations
    exploreByTitle: 'Explore by',
    citiesTitle: 'Cities',
    citiesDescription: 'Discover the best real estate opportunities in Algeria\'s main cities',
    discoverCity: 'Discover',
    allCitiesAvailable: 'All available cities',
    moreThanCitiesAvailable: 'More than 20 cities available',
    showLess: 'Show Less',
    seeAllCities: 'See All Cities',
    
    // City descriptions
    algerDescription: 'Algeria\'s dynamic capital',
    oranDescription: 'Pearl of Western Algeria',
    constantineDescription: 'City of suspended bridges',
    annabaDescription: 'City of the jujube tree',
    setifDescription: 'City of the High Plains',
    tlemcenDescription: 'Pearl of the Maghreb',
    bejaiaDescription: 'Bride of the Mediterranean',
    blidaDescription: 'City of Roses',
    
    // Blog translations
    blogInsights: 'Blog & Insights',
    blogDescription: 'Stay updated with the latest trends, tips, and insights from Algeria\'s real estate market',
    stayUpdated: 'Stay Updated',
    newsletterDescription: 'Subscribe to our newsletter and never miss the latest real estate insights',
    enterEmail: 'Enter your email',
    subscribe: 'Subscribe',
    backToBlog: "Back to Blog",
    
    // Property types
    propertyVilla: 'Villa',
    propertyAppartement: 'Apartment', 
    propertyDuplex: 'Duplex',
    propertyMaison: 'House',
    propertyStudio: 'Studio',
    propertyLoft: 'Loft',
    propertyChambre: 'Room',
    propertySuite: 'Suite',
    propertyPenthouse: 'Penthouse',
    
    // Pricing units
    currencyDA: 'DZD',
    currencyPerMonth: 'DZD/month',
    currencyPerNight: 'DZD/night',

    // Property names
    villaMediterranean: "Mediterranean Villa",
    luxuryApartment: "Luxury Apartment",
    modernApartment: "Modern Apartment",
    villaModern: "Modern Villa",
    duplexFamily: "Family Duplex",
    traditionalHouse: "Traditional House",
    modernStudio: "Modern Studio",
    apartmentStanding: "Luxury Apartment",
    villaWithPool: "Villa with Pool",
    villaWithGarden: "Villa with Garden",
    studioCenterCity: "City Center Studio",
    individualHouse: "Individual House",
    newApartment: "New Apartment",
    industrialLoft: "Industrial Loft",
    studioShortStay: "Short Stay Studio",
    seaViewApartment: "Sea View Apartment",
    holidayVilla: "Holiday Villa",
    guestRoom: "Guest Room",
    modernLoft: "Modern Loft",
    familySuite: "Family Suite",
    penthouseSeaView: "Sea View Penthouse",

    // Locations
    algerAlgeria: "Algiers, Algeria",
    oranAlgeria: "Oran, Algeria",
    constantineAlgeria: "Constantine, Algeria",
    tlemcenAlgeria: "Tlemcen, Algeria",
    setifAlgeria: "Setif, Algeria",
    bejaiaAlgeria: "Bejaia, Algeria",
    annabaAlgeria: "Annaba, Algeria",
    tipazaAlgeria: "Tipaza, Algeria",
    algerCentreAlgeria: "Algiers Center, Algeria",

    publishedBy: 'Published by',
    readMore: 'Read more',
    
    // Additional translations
    habitants: 'inhabitants',
    algeria: 'Algeria',
    tenthCentury: '10th century',
    thirdMillenniumBC: '3rd millennium BC',
    twelfthCenturyBC: '12th century BC',
    
    // City names
    cityAlger: 'Algiers',
    cityOran: 'Oran',
    cityConstantine: 'Constantine',
    cityAnnaba: 'Annaba',
    citySetif: 'Setif',
    cityTlemcen: 'Tlemcen',
    cityBejaia: 'Bejaia',
    cityBlida: 'Blida',

    // Metrics labels
    verifiedLabel: "100% verified",
    ratingLabel: "4.8/5 rating", 
    responseTimeLabel: "≤ 2h response",
    hoursAbbrev: "h",
    whyChooseDesc: "Discover why thousands of users trust us for their real-estate projects.",

    // Service CTAs
    exploreBuy: "Explore Buy",
    exploreRent: "Explore Rent", 
    exploreShortStay: "Explore Short Stay",

    // Buy bullets
    buy_feat_verified: "All properties & users verified",
    buy_feat_virtualTour: "Virtual tour",
    buy_feat_financing: "Easy financing",
    buy_feat_legal: "Legal support",

    // Rent bullets
    rent_feat_secureContracts: "Secure contracts",
    rent_feat_paymentGuarantee: "Payment guarantee",
    rent_feat_digitalInspection: "Digital check-in/out report",
    rent_feat_dedicatedTeam: "A dedicated team for you",

    // Short Stay bullets
    stay_feat_verifiedHosts: "Verified hosts",
    stay_feat_instantBooking: "Instant booking",
    stay_feat_localExperiences: "Local experiences",
    stay_feat_travelInsurance: "Travel insurance",
    
    // City page sections
    historyHeritage: 'History & Heritage',
    population: 'Population',
    inhabitantsShort: 'inhabitants',
    cityArea: 'Area',
    foundedIn: 'Founded in',
    propertiesAvailableIn: 'Properties available in',
    
    // City histories
    oranHistory: 'Oran is a coastal city in north-western Algeria known for its port, raï music scene, and a blend of French and Spanish architecture. Its modern corniche and historic quarters make it a cultural hub.',
    algerHistory: 'Algiers, the capital, mixes Ottoman, French colonial, and modern influences; the Casbah is a UNESCO World Heritage site.',
    constantineHistory: 'Constantine is famed for its dramatic gorges and suspension bridges, shaping its urban form and history.',
    annabaHistory: 'Annaba, on the Mediterranean, is known for its beaches, Saint Augustine heritage, and a growing port economy.',
    
    // Blog categories
    allCategories: 'All',
    marketTrends: 'Market Trends',
    buyingGuide: 'Buying Guide',
    investment: 'Investment',
    finance: 'Finance',
    renovation: 'Renovation',
    legal: 'Legal',
    
    // Blog post titles
    blogTitle1: 'The Future of Real Estate in Algeria',
    blogTitle2: 'How to Choose the Perfect Property Location',
    blogTitle3: 'Short-Stay Rentals: A Growing Opportunity',
    blogTitle4: 'Understanding Property Valuation in Algeria',
    blogTitle5: 'Renovation Tips for Maximum ROI',
    blogTitle6: 'Legal Considerations for Property Buyers',
    
    // Blog excerpts
    blogExcerpt1: 'Discover the emerging trends and opportunities in Algeria\'s growing real estate market.',
    blogExcerpt2: 'A comprehensive guide to selecting the ideal location for your next property investment.',
    blogExcerpt3: 'Explore the booming short-term rental market and how to maximize your investment returns.',
    blogExcerpt4: 'Learn the key factors that determine property values in different Algerian cities.',
    blogExcerpt5: 'Smart renovation strategies that can significantly increase your property\'s value.',
    blogExcerpt6: 'Essential legal aspects every property buyer should know before making a purchase.',
    
    // Blog authors
    author1: 'Sarah Benali',
    author2: 'Ahmed Mansouri', 
    author3: 'Fatima Ouali',
    author4: 'Karim Hakim',
    author5: 'Leila Benaissa',
    author6: 'Mohamed Kaci',

    // Host dashboard translations
    host: {
      dashboard: 'Dashboard',
      welcomeMessage: 'Welcome to your host space',
      activeProperties: 'Active properties',
      messagesReceived: 'Messages received',
      monthlyRevenue: 'Revenue this month',
      checkMessages: 'Check your messages',
      quickActions: 'Quick actions',
      publishProperty: 'Publish property',
      viewListings: 'View my listings',
      messages: 'Messages',
      recentProperties: 'Recent properties',
      publishedOn: 'Published on',
      active: 'Active',
      inactive: 'Inactive',
      loadingProperties: 'Loading your properties...',
      // Listings page
      listings: 'My Listings',
      manageProperties: 'Manage your properties and their performance',
      newListing: 'New Listing',
      postProperty: 'Post Property',
      activeListings: 'Active Listings',
      totalMessages: 'Total Messages',
      totalViews: 'Total Views',
      thisMonth: 'This month',
      view: 'View',
      edit: 'Edit',
      createdOn: 'Created on',
      noListingsYet: 'No listings yet',
      createFirstListing: 'Create your first listing to start receiving inquiries',
      createMyFirstListing: 'Create my first listing',
      confirmDelete: 'Are you sure you want to delete this property?',
      // Messages page
      messagesPage: 'Messages',
      manageContactRequests: 'Manage contact requests for your properties',
      unreadMessages: 'Unread messages',
      responseRate: 'Response rate',
      newStatus: 'New',
      readStatus: 'Read',
      repliedStatus: 'Replied',
      archivedStatus: 'Archived',
      markAsRead: 'Mark as read',
      reply: 'Reply',
      call: 'Call',
      archive: 'Archive',
      noMessages: 'No messages',
      noContactRequests: 'You have not received any contact requests yet.',
      loadingMessages: 'Loading messages...',
      calendar: 'Property Calendar'
    },
    
    satisfactionRate: 'Satisfaction Rate',
    back: 'Back',
    selectCurrency: 'Select Currency',
    preferences: 'Preferences',
    language: 'Language',
    currency: 'Currency',
    wishlist: 'Wishlist',
    settings: 'Settings',
    messages: 'Messages',
    getPersonalizedGuidance: 'Get personalized guidance from experts',

    // Admin translations
    admin: {
      dashboard: 'Dashboard',
      properties: 'Properties',
      users: 'Users',
      messages: 'Messages',
      settings: 'Settings',
      hostsGuests: 'Hosts & Guests',
      administration: 'Administration',
      adminConsole: 'Admin Console',
      backToSite: 'Back to Site',
      logout: 'Logout',
      userManagement: 'User Management', 
      manageUsersHosts: 'Manage users, hosts and their statuses',
      newUser: 'New User',
      totalUsers: 'Total Users',
      ofTotal: 'of total',
      allRoles: 'All roles',
      allStatuses: 'All statuses', 
      searchByNameEmail: 'Search by name or email...',
      adminPanel: 'Admin Panel',
      overviewPlatform: 'Overview of your platform performance',
      totalProperties: 'Total Properties',
      activeProperties: 'Active Properties',
      recentProperties: 'Recent Properties',
      propertyDistribution: 'Property Distribution',
      propertyManagement: 'Property Management',
      manageAllProperties: 'Manage all properties on the platform',
      export: 'Export',
      newProperty: 'New Property',
      totalRegistered: 'Total registered',
      needsValidation: 'Needs validation',
      issuesDetected: 'Issues detected',
      searchByTitle: 'Search by title, owner or location...',
      searchByName: 'Search by name or email...',
      allStatus: 'All Status',
      allTypes: 'All Types',
      active: 'Active',
      activeHosts: 'Active Hosts',
      pending: 'Pending',
      suspended: 'Suspended',
      forSale: 'For Sale',
      forRent: 'For Rent',
      shortStay: 'Short Stay',
      view: 'View',
      thisMonth: 'this month',
      propertiesPublished: 'Properties published',
      fromLastWeek: 'from last week'
    }
  },
  AR: {
    // Navigation
    home: 'الرئيسية',
    buy: 'شراء',
    rent: 'إيجار',
    shortStay: 'إقامة قصيرة',
    findDreamProperty: 'اعثر على عقارك المثالي',
    buyHeroDescription: 'اكتشف عقارات استثنائية للبيع في جميع أنحاء الجزائر مع إرشادات خبرائنا.',
    findPerfectRental: 'اعثر على إيجارك المثالي',
    rentHeroDescription: 'استكشف عقارات إيجار عالية الجودة تتناسب مع نمط حياتك وميزانيتك.',
    findPerfectStay: 'اعثر على إقامتك المثالية',
    shortStayHeroDescription: 'احجز أماكن إقامة فريدة لإقامات قصيرة لا تُنسى في جميع أنحاء الجزائر.',
    about: 'حول',
    blog: 'المدونة',
    login: 'تسجيل الدخول',
    publishProperty: 'نشر عقار',
    myProfile: 'ملفي الشخصي',
    myBookings: 'حجوزاتي',
    logout: 'تسجيل الخروج',
    
    // Hero
    heroTitle: 'هولي بايت',
    heroSubtitle: 'اشتري. استأجر. عش الجزائر بشكل مختلف.',
    heroDescription: 'أول منصة عقارية رقمية من الجيل الجديد للجزائر.',
    
    // Quick Access
    buyProperty: 'شراء عقار',
    rentProperty: 'استئجار منزل',
    shortStayProperty: 'إقامة قصيرة',
    start: 'ابدأ',
    bookNow: 'احجز الآن',
    
    // Property
    bedrooms: 'غرف النوم',
    bathrooms: 'دورات المياه',
    area: 'المساحة',
    
    // Common
    search: 'بحث',
    cancel: 'إلغاء',
    save: 'حفظ',
    clear: 'مسح',
    viewDetails: 'عرض التفاصيل',
    from: 'من',
    to: 'إلى',
    selectDate: 'اختر التاريخ',
    selectDates: 'اختر التواريخ',
    
    // Login
    loginSuccess: 'تم تسجيل الدخول بنجاح!',
    loginSuccessDesc: 'أنت الآن متصل بحساب هولي بايت الخاص بك.',
    loginDescription: 'سجل الدخول إلى حساب هولي بايت',
    email: 'عنوان البريد الإلكتروني',
    emailPlaceholder: 'بريدك@الالكتروني.com',
    password: 'كلمة المرور',
    forgotPassword: 'نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    createAccount: 'إنشاء حساب',
    
    // Pages
    propertiesForSale: 'عقارات للبيع',
    propertiesForSaleDesc: 'اكتشف أفضل العقارات المتاحة للشراء',
    propertiesForRent: 'عقارات للإيجار',
    propertiesForRentDesc: 'اعثر على الإيجار المثالي',
    shortStayTitle: 'الإقامات القصيرة',
    shortStayDesc: 'أماكن إقامة مثالية لإقاماتك القصيرة',
    
    // Quick Access Section
    howCanWeHelp: 'كيف يمكننا مساعدتك؟',
    quickEntriesDesc: 'مداخل سريعة لجميع احتياجاتك العقارية',
    buyPropertyTitle: 'شراء عقار',
    buyPropertyDesc: 'اكتشف أفضل الفرص للبيع',
    buyPropertySubtitle: 'استثمار ومسكن رئيسي',
    rentPropertyTitle: 'استئجار منزل',
    rentPropertyDesc: 'اعثر على منزلك القادم',
    rentPropertySubtitle: 'إيجار طويل المدى',
    shortStayTitle2: 'إقامة قصيرة',
    shortStayDesc2: 'احجز إقامتك لبضع ليال',
    shortStaySubtitle: 'إجازات ورحلات عمل',
    needHelp: 'تحتاج مساعدة في اتخاذ القرار؟',
    speakToAdvisor: 'تحدث إلى مستشار',
    
    // Services Section
    threeWaysToLive: 'ثلاث طرق للعيش في الجزائر',
    liveAlgeria: 'للعيش في الجزائر',
    platformDesc: 'منصة فريدة لجميع احتياجاتك العقارية. سواء كنت تبحث عن الشراء أو الإيجار أو الإقامة، نحن ندعمك بثقة وشفافية.',
    buyTitle: 'شراء',
    buySubtitle: 'اعثر على منزل المستقبل',
    buyDescription: 'اكتشف مجموعة مختارة بعناية من العقارات المتحققة. من الشقق في وسط المدينة إلى الفيلات على شاطئ البحر، اعثر على العقار الذي تحلم به في الجزائر.',
    rentTitle: 'إيجار',
    rentSubtitle: 'إيجار طويل المدى',
    rentDescription: 'سواء كنت طالبًا أو محترفًا أو عائلة، اعثر على الإيجار المثالي مع ضمانات الأمان وملاك موثوقين.',
    stayTitle: 'إقامة قصيرة',
    staySubtitle: 'إقامات قصيرة وإجازات',
    stayDescription: 'Airbnb الجزائري! احجز إقامتك المثالية لإجازاتك أو رحلات العمل أو الزيارات العائلية. أماكن إقامة فريدة وتجارب أصيلة.',
    explore: 'استكشف',
    whyChooseHolibayt: 'لماذا تختار هولي بايت؟',
    securityGuaranteed: 'الأمان مضمون',
    securityDesc: 'جميع عقاراتنا ومستخدمينا متحققون',
    premiumQuality: 'جودة ممتازة',
    qualityDesc: 'اختيار دقيق لرضاك',
    support247: 'دعم 24/7',
    supportDesc: 'فريق مخصص لخدمتك',
    
    // Home page sections
    seeAll: 'عرض الكل',
    trendingAreas: 'المناطق الرائجة',
    exploreByCities: 'استكشف حسب المدن',
    latestInsights: 'أحدث الأخبار',
    featuredListings: 'القوائم المميزة',
    findYourDreamHome: 'اعثر على منزل أحلامك',
    flexibleLiving: 'حياة مرنة',
    exploreVerifiedProperties: 'استكشف العقارات الموثقة',
    qualityRentalOptions: 'خيارات إيجار عالية الجودة',
    holidayRentals: 'إيجارات العطلات',
    perfectVacationStays: 'إقامات عطلة مثالية',
    
    // Hero placeholders and options
    cityNeighborhood: 'المدينة، الحي أو العنوان',
    whereToRent: 'أين تبحث عن الإيجار؟',
    stayDestination: 'وجهة إقامتك',
    propertyType: 'نوع العقار',
    apartment: 'شقة',
    house: 'منزل',
    villa: 'فيلا',
    land: 'أرض',
    maxBudget: 'الحد الأقصى للميزانية',
    housingType: 'نوع السكن',
    studio: 'استوديو',
    room: 'غرفة',
    maxRentMonth: 'أقصى إيجار/شهر',
    stayDates: 'تواريخ الإقامة',
    stayDuration: 'مدة الإقامة',
    night: 'ليلة',
    nights: 'ليال',
    quickSelection: 'اختيار سريع',
    oneNight: 'ليلة واحدة',
    oneWeek: 'أسبوع واحد',
    weekend: 'عطلة نهاية الأسبوع',
    oneMonth: 'شهر واحد',
    checkIn: 'تسجيل الوصول',
    checkOut: 'تسجيل المغادرة',
    travelers: 'المسافرون',
    availableProperties: 'العقارات المتاحة',
    satisfiedUsers: 'المستخدمون الراضون',
    wilayasCovered: 'الولايات المغطاة',
    
    // Footer translations
    footerDescription: 'منصتك العقارية الموثوقة في الجزائر',
    quickLinks: 'روابط سريعة',
    services: 'الخدمات',
    contact: 'اتصل بنا',
    propertyValuation: 'تقييم العقارات',
    legalSupport: 'الدعم القانوني',
    mortgageAdvice: 'نصائح الرهن العقاري',
    allRightsReserved: 'جميع الحقوق محفوظة',
    
    // About page translations
    aboutBeitik: 'حول هوليبايت',
    aboutDescription: 'هوليبايت هي منصة العقارات الرائدة في الجزائر، تربط المشترين والبائعين والمستأجرين لأكثر من 15 عامًا. مهمتنا هي تبسيط معاملاتك العقارية.',
    properties: 'العقارات',
    propertiesListed: 'العقارات المدرجة',
    clients: 'العملاء',
    satisfiedClients: 'العملاء الراضون',
    experience: 'الخبرة',
    years: 'سنة',
    realEstateExpertise: 'من الخبرة العقارية',
    security: 'الأمان',
    secureTransactions: 'معاملات آمنة',
    ourStory: 'قصتنا',
    storyParagraph1: 'تأسست بيتك في عام 2009، وثورت السوق العقاري الجزائري من خلال إنشاء أول منصة عبر الإنترنت مخصصة للعقارات في الجزائر.',
    storyParagraph2: 'بدأنا برؤية بسيطة: جعل العقارات في متناول الجميع وتسهيل المعاملات بين الأفراد والمهنيين.',
    storyParagraph3: 'اليوم، نحن فخورون بكوننا المنصة المرجعية مع أكثر من 10,000 عقار نشط ومجتمع من أكثر من 50,000 مستخدم.',
    storyParagraph4: 'يعمل فريق خبرائنا كل يوم لتحسين تجربتك ودعمك في مشاريعك العقارية.',
    ourMission: 'مهمتنا',
    missionDescription: 'إضفاء الطابع الديمقراطي على الوصول إلى العقارات في الجزائر من خلال تقديم منصة حديثة وآمنة وسهلة الاستخدام.',
    ourVision: 'رؤيتنا',
    visionDescription: 'أن نصبح المرجع الأساسي للعقارات في المغرب العربي وتحويل الطريقة التي يشتري ويستأجر بها الناس.',
    ourValues: 'قيمنا',
    valuesDescription: 'الشفافية والثقة والابتكار وخدمة العملاء الاستثنائية هي في قلب كل ما نقوم به.',
    
    // Publish property translations
    addPropertyDetails: 'أضف تفاصيل عقارك',
    propertyPublished: 'تم نشر العقار!',
    propertySubmittedSuccess: 'تم إرسال عقارك بنجاح وسيتم مراجعته قريبًا.',
    
    // Filter translations
    filters: 'المرشحات',
    clearAll: 'مسح الكل',
    allTypes: 'جميع الأنواع',
    villaFilter: 'فيلا',
    duplexFilter: 'دوبلكس',
    number: 'العدد',
    minArea: 'المساحة الدنيا (م²)',
    maxArea: 'المساحة القصوى (م²)',
    areaPlaceholder: 'مثال: 50',
    maxAreaPlaceholder: 'مثال: 200',
    minPrice: 'السعر الأدنى',
    maxPrice: 'السعر الأقصى',
    all: 'الكل',
    location: 'الموقع',
    cityOrDistrict: 'مدينة أو منطقة',
    
    // Property names and locations
    propertyNames: {
      luxuryApartment: 'شقة فاخرة',
      modernApartment: 'شقة عصرية',
      penthouse: 'بنتهاوس',
      seasideRental: 'إيجار على البحر',
      shortStay: 'إقامة قصيرة',
      studio: 'استوديو',
      traditionalHouse: 'منزل تقليدي',
      villaMediterranean: 'فيلا متوسطية'
    },
    propertyLocations: {
      algiers: 'الجزائر',
      oran: 'وهران',
      constantine: 'قسنطينة',
      annaba: 'عنابة',
      tlemcen: 'تلمسان',
      setif: 'سطيف',
      bejaia: 'بجاية',
      blida: 'البليدة',
      hydra: 'حيدرة',
      benAknoun: 'بن عكنون',
      birMouradRais: 'بير مراد رايس',
      elBiar: 'الأبيار',
      kouba: 'القبة',
      bachdjerrah: 'باش جراح',
      husseinDey: 'حسين داي',
      elHarrach: 'الحراش'
    },
    
    // Cities and additional translations
    followUs: 'تابعنا',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfUse: 'شروط الاستخدام',
    cookies: 'ملفات تعريف الارتباط',
    
    // Contact advisor translations
    chooseContactMethod: 'اختر طريقة الاتصال المفضلة لديك',
    multipleWaysConnect: 'طرق متعددة للتواصل مع مستشارينا الخبراء',
    phoneSupport: 'الدعم الهاتفي',
    speakDirectly: 'تحدث مباشرة مع مستشارينا',
    emailSupport: 'الدعم عبر البريد الإلكتروني',
    getDetailedAssistance: 'احصل على مساعدة مفصلة عبر البريد الإلكتروني',
    liveChat: 'الدردشة المباشرة',
    instantMessaging: 'مراسلة فورية مع فريقنا',
    chatNow: 'ادردش الآن',
    available247: 'متاح 24/7',
    responseWithin2h: 'الرد خلال ساعتين',
    onlineNow: 'متصل الآن',
    expertAdvisors: 'مستشارون خبراء',
    averageRating: 'التقييم المتوسط',
    averageResponseTime: 'متوسط وقت الاستجابة',
    sendMessage: 'أرسل رسالة',
    fullName: 'الاسم الكامل',
    yourFullName: 'اسمك الكامل',
    phoneNumber: 'رقم الهاتف',
    subject: 'الموضوع',
    whatCanWeHelp: 'كيف يمكننا مساعدتك؟',
    message: 'الرسالة',
    tellUsMore: 'أخبرنا المزيد عن احتياجاتك العقارية...',
    ourOffice: 'مكتبنا',
    businessHours: 'ساعات العمل',
    mondayFriday: 'الاثنين - الجمعة: 8:00 صباحًا - 8:00 مساءً',
    saturday: 'السبت: 9:00 صباحًا - 6:00 مساءً',
    sunday: 'الأحد: 10:00 صباحًا - 4:00 مساءً',
    needImmediateHelp: 'تحتاج مساعدة فورية؟',
    call247Hotline: 'اتصل بخط الطوارئ الخاص بنا على مدار الساعة',
    
    // Property and publish property translations  
    propertyTypeTranslation: 'نوع العقار',
    forSale: 'للبيع',
    forRent: 'للإيجار',
    shortStayRent: 'إقامة قصيرة',
    basicInformation: 'المعلومات الأساسية',
    propertyTitleField: 'عنوان العقار',
    propertyTitlePlaceholder: 'مثال: فيلا جميلة مع حديقة',
    categoryField: 'الفئة',
    selectCategory: 'اختر الفئة',
    duplex: 'دوبلكس',
    hotel: 'فندق',
    guesthouse: 'بيت ضيافة',
    locationField: 'الموقع',
    cityField: 'المدينة',
    district: 'المنطقة/الحي',
    fullAddress: 'العنوان الكامل',
    propertyDetailsTitle: 'تفاصيل العقار',
    chambers: 'غرف النوم',
    numberField: 'العدد',
    areaField: 'المساحة (م²)',
    floorField: 'الطابق',
    floorExample: 'مثال: الثاني',
    pricing: 'التسعير',
    priceDZD: 'السعر (دج)',
    priceExample: 'مثال: 2,500,000',
    priceTypeField: 'نوع السعر',
    totalPrice: 'السعر الإجمالي',
    monthlyPrice: 'شهريًا',
    dailyPrice: 'يوميًا',
    weeklyPrice: 'أسبوعيًا',
    featuresAmenities: 'الميزات والتجهيزات',
    parkingFeature: 'موقف سيارات',
    swimmingPoolFeature: 'مسبح',
    gardenFeature: 'حديقة',
    balconyFeature: 'شرفة',
    elevatorFeature: 'مصعد',
    securityFeature: 'أمان',
    furnishedFeature: 'مفروش',
    airConditioningFeature: 'تكييف',
    gymFeature: 'صالة رياضية',
    descriptionField: 'الوصف',
    detailedDescription: 'وصف مفصل',
    describeProperty: 'صف عقارك بالتفصيل...',
    contactInformationTitle: 'معلومات الاتصال',
    fullNameField: 'الاسم الكامل',
    phoneNumberField: 'رقم الهاتف',
    propertyPhotos: 'صور العقار',
    uploadPhotos: 'ارفع صورك',
    dragDropImages: 'اسحب وأفلت صورك هنا أو انقر للاختيار (حد أقصى 10 صور)',
    selectImages: 'اختر الصور',
    publishPropertyBtn: 'نشر العقار',
    completed: 'مكتمل',
    incompleteStep: 'خطوة غير مكتملة',
    completeRequiredFields: 'يرجى إكمال جميع الحقول المطلوبة',
    next: 'التالي',
    previous: 'السابق',
    
    // Property page translations
    contactOwner: 'الاتصال بالمالك',
    characteristics: 'الخصائص',
    listingDetails: 'تفاصيل الإعلان',
    reference: 'المرجع',
    typeField: 'النوع',
    publishedOn: 'نُشر في',
    lastUpdated: 'آخر تحديث',
    daysAgo: 'منذ يومين',
    
    // Cities translations
    exploreByTitle: 'استكشف حسب',
    citiesTitle: 'المدن',
    citiesDescription: 'اكتشف أفضل الفرص العقارية في المدن الرئيسية بالجزائر',
    discoverCity: 'اكتشف',
    allCitiesAvailable: 'جميع المدن المتاحة',
    moreThanCitiesAvailable: 'أكثر من 20 مدينة متاحة',
    showLess: 'إظهار أقل',
    seeAllCities: 'رؤية جميع المدن',
    
    // City descriptions
    algerDescription: 'العاصمة النشطة للجزائر',
    oranDescription: 'لؤلؤة الغرب الجزائري',
    constantineDescription: 'مدينة الجسور المعلقة',
    annabaDescription: 'مدينة النبق',
    setifDescription: 'مدينة الهضاب العليا',
    tlemcenDescription: 'لؤلؤة المغرب الأوسط',
    bejaiaDescription: 'عروس البحر الأبيض المتوسط',
    blidaDescription: 'مدينة الورود',
    
    // Blog translations
    blogInsights: 'المدونة والرؤى',
    blogDescription: 'ابق على اطلاع بأحدث الاتجاهات والنصائح والرؤى من سوق العقارات الجزائري',
    stayUpdated: 'ابق مطلعاً',  
    newsletterDescription: 'اشترك في نشرتنا الإخبارية ولا تفوت أحدث الرؤى العقارية',
    enterEmail: 'أدخل بريدك الإلكتروني',
    subscribe: 'اشتراك',
    backToBlog: "العودة للمدونة",
    
    // Property types
    propertyVilla: 'فيلا',
    propertyAppartement: 'شقة', 
    propertyDuplex: 'دوبلكس',
    propertyMaison: 'منزل',
    propertyStudio: 'استوديو',
    propertyLoft: 'لوفت',
    propertyChambre: 'غرفة',
    propertySuite: 'جناح',
    propertyPenthouse: 'بنتهاوس',
    
    // Pricing units
    currencyDA: 'دج',
    currencyPerMonth: 'دج/الشهر',
    currencyPerNight: 'دج/الليلة',

    // Property names
    villaMediterranean: "فيلا البحر الأبيض المتوسط",
    luxuryApartment: "شقة فاخرة",
    modernApartment: "شقة حديثة",
    villaModern: "فيلا حديثة",
    duplexFamily: "دوبلكس عائلي",
    traditionalHouse: "منزل تقليدي",
    modernStudio: "استوديو حديث",
    apartmentStanding: "شقة فاخرة",
    villaWithPool: "فيلا مع مسبح",
    villaWithGarden: "فيلا مع حديقة",
    studioCenterCity: "استوديو وسط المدينة",
    individualHouse: "منزل منفرد",
    newApartment: "شقة جديدة",
    industrialLoft: "لوفت صناعي",
    studioShortStay: "استوديو إقامة قصيرة",
    seaViewApartment: "شقة بإطلالة بحرية",
    holidayVilla: "فيلا عطلات",
    guestRoom: "غرفة ضيافة",
    modernLoft: "لوفت حديث",
    familySuite: "جناح عائلي",
    penthouseSeaView: "بنتهاوس بإطلالة بحرية",

    // Locations
    algerAlgeria: "الجزائر، الجزائر",
    oranAlgeria: "وهران، الجزائر",
    constantineAlgeria: "قسنطينة، الجزائر",
    tlemcenAlgeria: "تلمسان، الجزائر",
    setifAlgeria: "سطيف، الجزائر",
    bejaiaAlgeria: "بجاية، الجزائر",
    annabaAlgeria: "عنابة، الجزائر",
    tipazaAlgeria: "تيبازة، الجزائر",
    algerCentreAlgeria: "وسط الجزائر، الجزائر",

    publishedBy: 'نشر بواسطة',
    readMore: 'اقرأ المزيد',
    
    // Additional translations
    habitants: 'ساكن',
    algeria: 'الجزائر',
    tenthCentury: 'القرن العاشر',
    thirdMillenniumBC: 'الألفية الثالثة ق.م.',
    twelfthCenturyBC: 'القرن الثاني عشر ق.م.',
    
    // City names
    cityAlger: 'الجزائر',
    cityOran: 'وهران',
    cityConstantine: 'قسنطينة',
    cityAnnaba: 'عنابة',
    citySetif: 'سطيف',
    cityTlemcen: 'تلمسان',
    cityBejaia: 'بجاية',
    cityBlida: 'البليدة',

    // Metrics labels
    verifiedLabel: "موثَّق 100٪",
    ratingLabel: "تقييم 4.8/5",
    responseTimeLabel: "استجابة ≤ ساعتين",
    hoursAbbrev: "س",
    whyChooseDesc: "اكتشف لماذا يثق بنا الآلاف في مشاريعهم العقارية.",

    // Service CTAs
    exploreBuy: "استكشف شراء",
    exploreRent: "استكشف إيجار",
    exploreShortStay: "استكشف إقامة قصيرة",

    // Buy bullets
    buy_feat_verified: "جميع عقاراتنا ومستخدمينا موثّقون",
    buy_feat_virtualTour: "جولة افتراضية",
    buy_feat_financing: "تمويل ميسّر",
    buy_feat_legal: "دعم قانوني",

    // Rent bullets
    rent_feat_secureContracts: "عقود آمنة",
    rent_feat_paymentGuarantee: "ضمان الدفع",
    rent_feat_digitalInspection: "تقرير فحص رقمي",
    rent_feat_dedicatedTeam: "فريق مخصص لخدمتك",

    // Short Stay bullets
    stay_feat_verifiedHosts: "مضيفون موثّقون",
    stay_feat_instantBooking: "حجز فوري",
    stay_feat_localExperiences: "تجارب محلية",
    stay_feat_travelInsurance: "تأمين سفر",
    
    // City page sections
    historyHeritage: 'التاريخ والتراث',
    population: 'السكان',
    inhabitantsShort: 'نسمة',
    cityArea: 'المساحة',
    foundedIn: 'تأسست في',
    propertiesAvailableIn: 'العقارات المتاحة في',
    
    // City histories
    oranHistory: 'وهران مدينة ساحلية في شمال غرب الجزائر، معروفة بمينائها وموسيقى الراي ومزيج من العمارة الفرنسية والإسبانية. كورنيشها الحديث وأحياؤها التاريخية يجعلونها مركزًا ثقافيًا.',
    algerHistory: 'الجزائر العاصمة تمزج بين التأثيرات العثمانية والاستعمارية الفرنسية والحديثة؛ القصبة موقع تراث عالمي لليونسكو.',
    constantineHistory: 'قسنطينة مشهورة بأوديتها العميقة وجسورها المعلقة التي شكّلت تاريخها وعمرانها.',
    annabaHistory: 'عنابة على المتوسط معروفة بشواطئها وإرث القديس أوغسطين ومينائها المتنامي.',
    
    // Blog categories
    allCategories: 'الكل',
    marketTrends: 'اتجاهات السوق',
    buyingGuide: 'دليل الشراء',
    investment: 'الاستثمار',
    finance: 'التمويل',
    renovation: 'التجديد',
    legal: 'قانوني',
    
    // Blog post titles
    blogTitle1: 'مستقبل العقارات في الجزائر',
    blogTitle2: 'كيفية اختيار الموقع المثالي للعقار',
    blogTitle3: 'الإيجار قصير المدى: فرصة متنامية',
    blogTitle4: 'فهم تقييم العقارات في الجزائر',
    blogTitle5: 'نصائح التجديد لتحقيق أقصى عائد استثمار',
    blogTitle6: 'الاعتبارات القانونية لمشتري العقارات',
    
    // Blog excerpts
    blogExcerpt1: 'اكتشف الاتجاهات الناشئة والفرص في سوق العقارات الجزائري المتنامي.',
    blogExcerpt2: 'دليل شامل لاختيار الموقع المثالي لاستثمارك العقاري القادم.',
    blogExcerpt3: 'استكشف سوق الإيجار قصير المدى المزدهر وكيفية تعظيم عوائد استثمارك.',
    blogExcerpt4: 'تعلم العوامل الرئيسية التي تحدد قيم العقارات في مختلف المدن الجزائرية.',
    blogExcerpt5: 'استراتيجيات تجديد ذكية يمكنها زيادة قيمة عقارك بشكل كبير.',
    blogExcerpt6: 'الجوانب القانونية الأساسية التي يجب على كل مشتري عقار معرفتها قبل الشراء.',
    
    // Blog authors
    author1: 'سارة بن علي',
    author2: 'أحمد منصوري', 
    author3: 'فاطمة والي',
    author4: 'كريم حكيم',
    author5: 'ليلى بن عيسى',
    author6: 'محمد قاسي',
    
    callBtn: 'اتصال',
    sendMessageBtn: 'أرسل رسالة',

    // Property page specific keys
    locationTitle: "الموقع",
    mapboxHint: "لعرض الخريطة التفاعلية، أدخل مفتاح Mapbox العام. يمكنك الحصول عليه من",
    mapboxTokenPlaceholder: "مفتاح Mapbox العام",
    loadMap: "تحميل الخريطة",
    addressLabel: "العنوان",
    detailsLabel: "التفاصيل",
    nearbyShops: "متاجر",
    nearbyShopsNote: "قريب",
    transport: "النقل",
    transportAccessible: "متاح",

    // Property features
    privatePool: "مسبح خاص",
    landscapedGarden: "حديقة منسقة",
    garage2Cars: "مرآب لسيارتين",
    alarmSystem: "نظام إنذار",
    airConditioning: "تكييف هواء",
    equippedKitchen: "مطبخ مجهز",
    
    // Blog dates
    march15: "15 مارس 2024",
    march10: "10 مارس 2024", 
    march5: "5 مارس 2024",
    february28: "28 فبراير 2024",
    february20: "20 فبراير 2024",
    february15: "15 فبراير 2024",

    // Reading times
    readTime5: "10 دقائق قراءة",

    // Host dashboard translations
    host: {
      dashboard: 'لوحة القيادة',
      welcomeMessage: 'مرحباً بك في مساحة المضيف',
      activeProperties: 'العقارات النشطة',
      messagesReceived: 'الرسائل المستلمة',
      monthlyRevenue: 'الإيرادات هذا الشهر',
      checkMessages: 'راجع رسائلك',
      quickActions: 'إجراءات سريعة',
      publishProperty: 'نشر عقار',
      viewListings: 'عرض إعلاناتي',
      messages: 'الرسائل',
      recentProperties: 'العقارات الأحدث',
      publishedOn: 'نُشر في',
      active: 'نشط',
      inactive: 'غير نشط',
      loadingProperties: 'جاري تحميل عقاراتك...',
      // Listings page
      listings: 'قوائمي',
      manageProperties: 'إدارة عقاراتك وأدائها',
      newListing: 'قائمة جديدة',
      postProperty: 'نشر عقار',
      activeListings: 'القوائم النشطة',
      totalMessages: 'إجمالي الرسائل',
      totalViews: 'إجمالي المشاهدات',
      thisMonth: 'هذا الشهر',
      view: 'عرض',
      edit: 'تعديل',
      createdOn: 'تم الإنشاء في',
      noListingsYet: 'لا توجد قوائم بعد',
      createFirstListing: 'أنشئ قائمتك الأولى لبدء استقبال الاستفسارات',
      createMyFirstListing: 'إنشاء قائمتي الأولى',
      confirmDelete: 'هل أنت متأكد من حذف هذا العقار؟',
      // Messages page
      messagesPage: 'الرسائل',
      manageContactRequests: 'إدارة طلبات التواصل لعقاراتك',
      unreadMessages: 'رسائل غير مقروءة',
      responseRate: 'معدل الاستجابة',
      newStatus: 'جديد',
      readStatus: 'مقروء',
      repliedStatus: 'تم الرد',
      archivedStatus: 'مؤرشف',
      markAsRead: 'وضع علامة كمقروء',
      reply: 'رد',
      call: 'اتصال',
      archive: 'أرشفة',
      noMessages: 'لا توجد رسائل',
      noContactRequests: 'لم تتلق أي طلبات تواصل حتى الآن.',
      loadingMessages: 'جاري تحميل الرسائل...',
      calendar: 'تقويم العقارات'
    },
    
    satisfactionRate: 'معدل الرضا',
    back: 'رجوع',
    selectCurrency: 'اختيار العملة',
    preferences: 'التفضيلات',
    language: 'اللغة',
    currency: 'العملة',
    wishlist: 'المفضلة',
    settings: 'الإعدادات',
    messages: 'الرسائل',
    getPersonalizedGuidance: 'احصل على إرشادات مخصصة من الخبراء',
  }
};

const translations = allTranslations;

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);
function detectInitialLang(): Language {
  // 1) Check localStorage first for saved preference
  const savedLang = localStorage.getItem('lang');
  if (savedLang && (savedLang === 'EN' || savedLang === 'FR' || savedLang === 'AR')) {
    return savedLang as Language;
  }
  
  // 2) URL ?lang=en|fr|ar
  const urlLang = new URLSearchParams(window.location.search).get('lang');
  if (urlLang) {
    const up = urlLang.toUpperCase();
    if (up === 'EN' || up === 'FR' || up === 'AR') return up as Language;
  }
  
  // 3) Default to English for all users
  return 'EN';
}

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLang, setCurrentLang] = useState<Language>(detectInitialLang);

  // Persist choice and update <html> attributes
  useEffect(() => {
    localStorage.setItem('lang', currentLang);
    document.documentElement.lang = currentLang === 'AR' ? 'ar' : currentLang.toLowerCase();
    document.documentElement.dir = currentLang === 'AR' ? 'rtl' : 'ltr';
  }, [currentLang]);

  // Memoized translator for the active language
  const t = useMemo(() => {
    return (key: string): string | any => {
      const keys = key.split('.');
      let result: any = translations[currentLang];
      
      for (const k of keys) {
        if (result && typeof result === 'object' && k in result) {
          result = result[k];
        } else {
          // Hide raw keys in production, show them in development
          return import.meta.env.DEV ? key : '';
        }
      }
      
      return result;
    };
  }, [currentLang]);

  return (
    <LanguageContext.Provider value={{ currentLang, setCurrentLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
};